### ISSUE TITLE
openPMD extension for MD

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/ViNYL-project#18]

**Comment by ejcjason** [comment]
MD extension version 0.0.1
https://github.com/ejcjason/openPMD-standard/blob/EXT_MD/EXT_MD.md

**Comment by CFGrote** [comment]
Good work. Some comments:

- [ ] Remove references to SIMEX, not relevant
- [ ] Does this also work for other MD codes besides LAMMPS? Should be agnostic to the actual MD code
- [ ] You constantly refer to scope, but only a few items really mention it. Add scope everywhere
-[ ] The 2nd example under "edge" is not a cubic box (edges are not of same length) 
-[ ] Do you want to support storing coordinates in units of box edge vectors or unit cell vectors (primitve cell, conventional cell)? Up to you, just want to bring it up.

**Comment by ejcjason** [comment]
- Remove references to SIMEX, not relevant
   - Done
- Does this also work for other MD codes besides LAMMPS? Should be agnostic to the actual MD code
    - Yes. This standard should be agnostic to an actual MD code by design and not limited to LAMMPS. I've deleted the LAMMPS part to avoid the implication.
- You constantly refer to scope, but only a few items really mention it. Add scope everywhere
    - Done.
- The 2nd example under "edge" is not a cubic box (edges are not of same length)
    - Corrected. It is a triclinic box.
- Do you want to support storing coordinates in units of box edge vectors or unit cell vectors (primitve cell, conventional cell)? Up to you, just want to bring it up.
    - Yes, that's a good idea. Actually, I know some people using fractional coordinate quite often. This should be mentioned. Please see the new version:  https://github.com/ejcjason/openPMD-standard/blob/EXT_MD/EXT_MD.md
