### ISSUE TITLE
SIMEX docker

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/ViNYL-project#31]
We need to update the docker images for simex. The goal is to install simex on a cloud instance of jupyter hub (hosted on DESY's cloud servers). We also have to demonstrate that simex / vinyl example notebooks can be run on binder.

- [ ] move dependencies in top level cmake file to the Modules that actually cause these dependencies. 
- [ ] Document better how modules can be selected/deselected.
- [ ] Image for master
- [ ] Image for develop 
- [ ] repo2docker script
- [ ] at image build time, user should be able to select/deselect the modules he/she/* wants included in the image.

Useful contacts:
Thomas Kluyver (XFEL, WP4), Michael Schuh (DESY, expands)

**Comment by ejcjason** [comment]
I know that Thomas has tried working on it. I will ask Thomas about the status and work with him.

**Comment by ejcjason** [comment]
Any suggestions about priority? @CFGrote  Which one should have a higher priority? [Documentation](https://github.com/PaNOSC-ViNYL/ViNYL-project/issues/22) or this one?

**Comment by CFGrote** [comment]
documentation

--
Dr. Carsten Fortmann-Grote
PaNOSC WP5 leader

**Comment by CFGrote** [comment]
f5ab754 enabled installation via conda:
1) create a conda environment with
```
$> conda env create -n simex --file environment.yml
$> conda activate simex
```

2) install all libs into `$CONDA_PREFIX` with
```
$> ./install.sh conda
```

3) finally install the simex library
```
$> cd Sources/python
$> python -m pip install .
```

**Comment by CFGrote** [comment]
@JunCEEE @cloudbustinguk, what is the status here? can we close this one?

**Comment by cloudbustinguk** [comment]
AFAIK this can be closed.

**Comment by JunCEEE** [comment]
This can be closed.
