### ISSUE TITLE
pyvinyl intermediate API layer

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/ViNYL-project#34]
After completing the top level pyvinyl API (BaseCalculator/Parameters), we now have to define the intermediate APIs:
- [ ] PhotonSource
- [ ] NeutronSource
- [ ] PhotonPropagation
- [ ] NeutronPropagation
- [ ] RadiationMatterInteraction
- [ ] SignalGeneration
- [ ] Detector

Take the corresponding Calculators in SIMEX as templates. Move as many parameters as possible from the specialized parameter classes into the intermediate level. For each level, ensure the API documentation (autogenerated) is ok and add a usage example as a jupyter notebook.

**Comment by mads-bertelsen** [comment]
I don't see why an intermediate API layer is needed. If libpyvinyl provides a consistent interface and this is adopted in both SIMEX and McStasScript, we will have harmonised them as we set out to do, and hopefully made maintenance simpler.

What would be gained from this intermediate layer? It looks like a version of simex that just adds neutron scattering, but in a way that is not really compatible with how McStas works.

**Comment by shervin86** [comment]
Shall we close this issue?

**Comment by JunCEEE** [comment]
This seems obsoleted.
