### ISSUE TITLE
Update simex demo from 18M review for M5.2

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/ViNYL-project#40]

**Comment by CFGrote** [comment]
The Demo includes:

- Login on jupyter hub
- Duplicate a given simex tutorial notebook
- Open the notebook
- Select the simex kernel
- Execute the notebook as it is
- Change parameters according to new simulation setting
- Execute the new simulation
- Analyse the data in the notebook
- Publish the new simulation / data on gh / zenodo

**Comment by ejcjason** [comment]
1. SFX example based on https://github.com/ejcjason/crystalProject/tree/master/src/controller/panoscDEMO
2. SPI example

**Comment by ejcjason** [comment]
Create DEMO repo: https://github.com/PaNOSC-ViNYL/M5.2DEMO

**Comment by Jun-Chenge** [comment]
Two examples were created here. Please comment on what else to add.
https://github.com/PaNOSC-ViNYL/M5.2DEMO/tree/master/simex
