### ISSUE TITLE
Demo Oasys simulation as aservice for M5.2

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/ViNYL-project#42]

**Comment by aljosahafner** [comment]
Oasys running in RAFEC in VUO. Packages will be updated to reflect v0.1 of Wiser.

**Comment by aljosahafner** [comment]
This is the starting repo for openPMD extensions and future widgets from Panosc:
https://github.com/PaNOSC-ViNYL/OASYS1-PaNOSC

**Comment by aljosahafner** [comment]
Managed to setup testing environment, updated the openPMD widget.
