### ISSUE TITLE
Prepare a release for McStas script for D5.2

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/ViNYL-project#44]

**Comment by mads-bertelsen** [comment]
Prepared a release of McStasScript which is available here: https://pypi.org/project/McStasScript/

Updates:
- Fixed a bug preventing instrument visualization when input_path is used
- Added __str__ and __repr__ methods to McStasData and component objects

**Comment by mads-bertelsen** [comment]
The current release is version 0.0.21, this is suitable for our first Jupyter hub demo.

**Comment by cloudbustinguk** [comment]
If you want to give this one a go, it will save you 1GB.

https://github.com/cloudbustinguk/PaNOSC-ViNYL-McStas

**Comment by cloudbustinguk** [comment]
DockerHub image will also shortly be uploaded: https://hub.docker.com/r/cloudbusting/mcstasscript-cloudbusting
