### ISSUE TITLE
Prepare a release for Wiser for D5.2

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/ViNYL-project#46]

**Comment by aljosahafner** [comment]
https://pypi.org/project/OASYS1-OasysWiser/

It will be called either v1.0 (non-incremental boost) or v0.1 (if we decide for incremental update), currently at v0.0.20

**Comment by aljosahafner** [comment]
Features to implement:

[ ] Focus find

[ ] Focus sweep

[ ] Investigate why whole beamline propagation doesn't work (@srio maybe you can help?)

[ ] Get and set Figure error specifications

**Comment by srio** [comment]
Hi Aljosa, 
what do you mean "whole beamline propagation"? Does "Element by element" work?
Could you upload a workspace to check the problem? 
Thanks.

**Comment by aljosahafner** [comment]
Hey, yes, "Element by element" works, "whole beamline propagation" gives no result.

You can install v0.0.20 (the latest) through OASYS1-OasysWiser and then use this workspace (in zip because of github):
[Wiser_test_beamline.ows.zip](https://github.com/PaNOSC-ViNYL/ViNYL-project/files/5217894/Wiser_test_beamline.ows.zip)

**Comment by aljosahafner** [comment]
I am adding another "feature":

- [ ] Correct the axes of common plots to display correct values

**Comment by aljosahafner** [comment]
First two points are better explained here:
https://github.com/oasys-elettra-kit/OasysWiser/issues/5

**Comment by srio** [comment]
Regarding the "whole beamline propagation" I am sorry I cannot help much. You can have a look at the SRW add-on that implements it. You can also ask for advise to Luca Rebuffi that implemented that part also in wiser, if I remember well.

**Comment by aljosahafner** [comment]
Revised to do:
- [ ] Send an E-mail to L. Rebuffi about whole beamline propagation
- [ ] Inspect plots and units...

**Comment by aljosahafner** [comment]
Wiser released with features specified until now. Version was bumped to v0.1: https://pypi.org/project/OASYS1-OasysWiser/0.1.1/
