### ISSUE TITLE
libpyvinyl supports numpy arrays

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/ViNYL-project#76]
See https://github.com/PaNOSC-ViNYL/libpyvinyl/issues/25 for details

**Comment by shervin86** [comment]
And also https://github.com/PaNOSC-ViNYL/libpyvinyl/issues/24

**Comment by shervin86** [comment]
Implemented and merged in https://github.com/PaNOSC-ViNYL/libpyvinyl/pull/28
