### ISSUE TITLE
BaseData class

### ISSUE THREAD

**Issue by JunCEEE** [PaNOSC-ViNYL/ViNYL-project#77]
It's added here.

BaseData: https://github.com/PaNOSC-ViNYL/libpyvinyl/blob/dataAPI/libpyvinyl/BaseData.py

- [x] Finish an example

DiffractionData example: https://github.com/PaNOSC-ViNYL/libpyvinyl/blob/dataAPI/libpyvinyl/DiffractionData/DiffractionData.py
Usage: https://github.com/PaNOSC-ViNYL/libpyvinyl/blob/dataAPI/libpyvinyl/DiffractionData/testDiffractionData.py

Todos after the first pseudo-code review.

- [x] Implement Manuel's suggestion https://github.com/PaNOSC-ViNYL/libpyvinyl/issues/26#issuecomment-988320581
- [x] Make input a dictionary instead of a list, regardless of the number of input channels https://github.com/PaNOSC-ViNYL/libpyvinyl/pull/32#discussion_r764699646.
- [x] Set `base_path`, `input` and `output_suffix` through `__init__()` https://github.com/PaNOSC-ViNYL/libpyvinyl/pull/32#discussion_r764703423

Todos after the schematic discussion.
- [x] Add a wiki page of the overall picture.
- [x] A clear example of the smallest start-to-end simulation system.
     - [x] A functional libpyvinyl branch.
     - [x] A small start-to-end simulation system.

**Comment by shervin86** [comment]
I'm thinking about which class should be responsible for the output in openPMD format and it is not yet clear to me.
In openPMD there are several things that need to be written:
the data
some metadata from the instrument:
instrument name
git repository
commit hash
date
diff w.r.t. to the commited version (patch like)
parameter values
To me, it makes more sense to have a separate library taking care of the I/O taking in input the different information and the DataClass and taking care of putting in openPMD the things in the right place. If then there is a change in the openPMD standard things have to be touched in a single place and not in a multitude of classes

**Comment by JunCEEE** [comment]
In my mind, the DataClass takes care of the native output and input of the backengine and write/read them in openPMD (or other) format with an openPMD API. I guess the openPMD API is what you mean by the "separate library"? @shervin86

**Comment by shervin86** [comment]
I was thinking that it would be better to have the API to take the data class and write them. 
The data class should know nothing about the output format. 
I would make a package, that depends on the openPMD API and the libpyvinyl and performs the I/O.
If I understood correctly you are suggesting to add the openPMD API as a dependency to the libpyvinyl. I don't think this is good idea.

So I would do:
 - a data base class: defines abstract methods for reading the data from the backengine
 - advanced data class: one data class for wavefront data and one for raytracing
 - specific backengine specific data class that inherit from the advanced class and that implement the read of the data from the backengine 
 - a library that takes as input the data from either the wavefront type or raytracing type and outputs in openPMD format using the appropriate API based on the data type

**Comment by JunCEEE** [comment]
Oh, I'm sorry that I might not be clear enough. The openPMD API I mentioned was just a general idea for "An API to write in openPMD format" instead of the exact "openPMD API". It is exactly what you mean that "a package, that depends on the openPMD API and the libpyvinyl and performs the I/O". 

The example I made here: 
- [BaseData](https://github.com/PaNOSC-ViNYL/libpyvinyl/blob/dataAPI/libpyvinyl/BaseData.py) is the "data base class", it's actually a wrapper.
- [DiffractionData](https://github.com/PaNOSC-ViNYL/libpyvinyl/blob/dataAPI/libpyvinyl/DiffractionData/DiffractionData.py) is the  "advanced data class".
- I did your third point and fourth point together by defining a class for each format/backegine and wrap the formats belong to a certain data type (e.g. wavefront, raytracing, diffraction)  together under the "advanced data class". See  [testDiffractionData.py](https://github.com/PaNOSC-ViNYL/libpyvinyl/blob/dataAPI/libpyvinyl/DiffractionData/testDiffractionData.py)

In this way, we just need to implement your raytracing I/O package in an "openPMDFormat" class and it will be wrapped by an "raytacing data class".

**Comment by shervin86** [comment]
Great, then I totally misunderstood the meaning of the classes. I will look into it more carefully tomorrow.

**Comment by JunCEEE** [comment]
Todos after the first pseudo-code review.

- [ ] Implement Manuel's suggestion https://github.com/PaNOSC-ViNYL/libpyvinyl/issues/26#issuecomment-988320581
- [ ] Make input a dictionary instead of a list, regardless of the number of input channels https://github.com/PaNOSC-ViNYL/libpyvinyl/pull/32#discussion_r764699646.
- [ ] Set `base_path`, `input` and `output_suffix` through `__init__()` https://github.com/PaNOSC-ViNYL/libpyvinyl/pull/32#discussion_r764703423
